### PR TITLE
Fix deprecated methods of Chainer 1.24.0

### PR DESCRIPTION
**Pull request by massongit**
I fixed deprecated methods of Chainer 1.24.0: `chainer.cuda.get_device` and `bi_lstm.BiLSTM_CNN_CRF.zerograds` (`chainer.Chain.zerograds`).

### CODE REVIEW

**Comment by aonotas** [comment]
Thank you for your great PR!

**Comment by aonotas** [comment]
Could you fix your code to define own chainer util functions like followings:
```
# util_chainer.py
def my_cuda_get_device(cuda, device_id):
    if version < '2.0':
        cuda.get_device(device_id).use()
    else:
        # v2.0
        cuda.get_device_from_id(device_id).use()


def my_cleargrads(net):
    if version < '2.0':
        net.zerograds()
    else:
        # v2.0
        net.cleargrads()

```

**Comment by aonotas** [comment]
if you fix your code, I will merge it!
Thank you for your help :)

**Comment by massongit** [comment]
Thank you for your comments!

I think it is unnecessary to define own chainer util functions.
As the reason:
* This tool supports Chainer 2.1.0 and 1.24.0.
* `chainer.cuda.get_device` was deprecated on [Chainer 1.23.0](https://github.com/chainer/chainer/releases/tag/v1.23.0) (earlier Chainer 1.24.0).
* `chainer.Chain.zerograds` was deprecated on [Chainer 1.15.0](https://github.com/chainer/chainer/releases/tag/v1.15.0)  (earlier Chainer 1.24.0).

**Comment by aonotas** [comment]
OK! Thank you for your help :)
I will merge your PR.

**Pull request merged**
